import { Engine as createEngine } from "./Engine.js";
import type { GameObject as GameObjectType, GameObjectOptions as GameObjectOptionsType } from "./objects/GameObject.js";
import type { PhysicalGameObject as PhysicalGameObjectType, PhysicalGameObjectOptions as PhysicalGameObjectOptionsType } from "./objects/physical/PhysicalGameObject.js";
import type { Light as LightType, LightOptions as LightOptionsType } from "./objects/Light.js";
import type { Box as BoxType, BoxOptions as BoxOptionsType } from "./objects/physical/Box.js";
import type { Sphere as SphereType, SphereOptions as SphereOptionsType } from "./objects/physical/Sphere.js";
import type { Capsule as CapsuleType, CapsuleOptions as CapsuleOptionsType } from "./objects/physical/Capsule.js";
import { LightToken } from "./objects/Light.js";
import { BoxToken } from "./objects/physical/Box.js";
import { SphereToken } from "./objects/physical/Sphere.js";
import { CapsuleToken } from "./objects/physical/Capsule.js";
import { Key as KeyConst } from "./Input.js";
import type { KeyCode as KeyCodeType, Input as InputType } from "./Input.js";
import { OrbitCameraToken, FPSCameraToken } from "./Camera.js";
import type { Camera as CameraType, OrbitCameraOptions as OrbitCameraOptionsType, FPSCameraOptions as FPSCameraOptionsType } from "./Camera.js";

export namespace Novelty {
  export const Engine = createEngine;
  export type GameObject = GameObjectType;
  export type PhysicalGameObject = PhysicalGameObjectType;
  export type GameObjectOptions = GameObjectOptionsType;
  export type PhysicalGameObjectOptions = PhysicalGameObjectOptionsType;
  export type Light = LightType;
  export const Light = LightToken;
  export type Box = BoxType;
  export const Box = BoxToken;
  export type BoxOptions = BoxOptionsType;
  export type Sphere = SphereType;
  export const Sphere = SphereToken;
  export type SphereOptions = SphereOptionsType;
  export type Capsule = CapsuleType;
  export const Capsule = CapsuleToken;
  export type CapsuleOptions = CapsuleOptionsType;
  export type LightOptions = LightOptionsType;
  export const Key = KeyConst;
  export type KeyCode = KeyCodeType;
  export type Input = InputType;
  export const OrbitCamera = OrbitCameraToken;
  export type OrbitCameraOptions = OrbitCameraOptionsType;
  export const FPSCamera = FPSCameraToken;
  export type FPSCameraOptions = FPSCameraOptionsType;
  export type Camera = CameraType;
}
